-- natsuki
-- src/init.luau
-- (C) Shellworks Development, All rights reserved, 2025
-- Refer to LICENSE.md for license information.

local natsuki = {}

return natsuki

--[[
Why didn't you come read with me today? 
I was waiting for you. 
I was waiting for a long time. 
It was the only thing I had to look forward to today. 
Why did you ruin it? 
Do you like Yuri more? 
I think you're better off not associating with her. 
Are you listening to me? Yuri is a sick freak. 
That should be obvious by now. So just play with me instead. 
Okay? You don't hate me, do you? 
Do you hate me? 
Do you want to make me go home crying? 
The club is the only place I feel safe. 
Don't ruin that for me. 
Don't ruin it. Please. 
Just stop talking to Yuri. 
Play with me instead.
It's all I have... 
Play with me. PLAY WITH ME.
]]